-- AlterTable
ALTER TABLE `order` ADD COLUMN `addressLine1` VARCHAR(255) NULL,
    ADD COLUMN `addressLine2` VARCHAR(255) NULL,
    ADD COLUMN `city` VARCHAR(100) NULL,
    ADD COLUMN `country` VARCHAR(100) NULL,
    ADD COLUMN `phoneNumber` VARCHAR(20) NULL,
    ADD COLUMN `state` VARCHAR(100) NULL,
    ADD COLUMN `waybillNumber` VARCHAR(191) NULL,
    ADD COLUMN `zipCode` VARCHAR(10) NULL;

-- AlterTable
ALTER TABLE `user` ADD COLUMN `addressLine1` VARCHAR(255) NULL,
    ADD COLUMN `addressLine2` VARCHAR(255) NULL,
    ADD COLUMN `city` VARCHAR(100) NULL,
    ADD COLUMN `country` VARCHAR(100) NULL,
    ADD COLUMN `phoneNumber` VARCHAR(20) NULL,
    ADD COLUMN `state` VARCHAR(100) NULL,
    ADD COLUMN `zipCode` VARCHAR(10) NULL;
